#!/usr/bin/env bash
# Phase 2 (+ feature overlays): apply the WraithLink rebrand and customizations
# onto the synced source tree.
. "$(dirname "$0")/lib.sh"
load_config

cd "$WL_SRC_DIR" || die "Source not found at ${WL_SRC_DIR} - run 01-sync-source.sh first."

log "Rebrand dry-run (preview)..."
"${WL_ROOT}/rebrand/rebrand.sh" "$WL_SRC_DIR" "$WL_OTA_URL"

log "Applying rebrand..."
"${WL_ROOT}/rebrand/rebrand.sh" "$WL_SRC_DIR" "$WL_OTA_URL" --apply
ok "Rebrand applied."

# Feature overlays (each idempotent and self-contained). Order matters:
# static overlays + apps first, then first-boot rendering (which globs fragments).
for f in \
  "${WL_ROOT}/overlays/apply-network-privacy.sh" \
  "${WL_ROOT}/apps/apply-bundled-apps.sh" \
  "${WL_ROOT}/apps/setup/apply-setup-app.sh" \
  "${WL_ROOT}/x47-link/apply-x47-client.sh" \
  "${WL_ROOT}/overlays/apply-framework-patches.sh" \
  "${WL_ROOT}/overlays/apply-media-privacy.sh" \
  "${WL_ROOT}/overlays/apply-firstboot.sh" ; do
  if [ -x "$f" ]; then
    log "Overlay: $(basename "$f")"
    "$f" "$WL_SRC_DIR"
  else
    warn "Overlay missing/not executable, skipping: $f"
  fi
done

# Aggregate every generated product fragment into one inheritable makefile.
log "Generating aggregate product makefile vendor/wraithlink/wraithlink.mk"
agg="${WL_SRC_DIR}/vendor/wraithlink/wraithlink.mk"
{
  echo "# WraithLink aggregate product makefile (generated by 04-apply-rebrand.sh)."
  echo "# Inherit from your device product config:"
  echo "#   \$(call inherit-product, vendor/wraithlink/wraithlink.mk)"
  for frag in "${WL_SRC_DIR}"/vendor/wraithlink/wraithlink-*.mk; do
    [ -f "$frag" ] || continue
    echo "include ${frag#${WL_SRC_DIR}/}"
  done
} > "$agg"
ok "Wrote $agg"

# Ensure the device product makefile inherits our aggregate. For GrapheneOS+adevtool,
# the product config is the generated vendor/google_devices/<device>/<device>.mk, which
# a vendor re-extraction (02) would overwrite - so we (re-)inject idempotently on every
# apply. This makes the integration self-healing instead of a fragile manual edit.
dev_mk="${WL_SRC_DIR}/vendor/google_devices/${WL_DEVICE}/${WL_DEVICE}.mk"
inherit_line='$(call inherit-product, vendor/wraithlink/wraithlink.mk)'
if [ -f "$dev_mk" ]; then
  if grep -qF "vendor/wraithlink/wraithlink.mk" "$dev_mk"; then
    ok "Device product config already inherits wraithlink.mk (${dev_mk#${WL_SRC_DIR}/})"
  else
    printf '\n# WraithLink customizations (added by 04-apply-rebrand.sh)\n%s\n' "$inherit_line" >> "$dev_mk"
    ok "Injected inherit-product into ${dev_mk#${WL_SRC_DIR}/}"
  fi
else
  warn "Device product makefile not found at ${dev_mk}."
  warn "Manually add to your ${WL_DEVICE} product config: ${inherit_line}"
fi

warn "First-boot provisioning is handled by the WraithLinkSetup app - no SELinux domain needed."
ok "All WraithLink customizations applied. Next: scripts/05-build.sh"
