#!/usr/bin/env bash
# Phase 5: fetch redistributable APKs, VERIFY their signatures, and wire them +
# the WraithLink Store into the product as preinstalled/updatable system apps.
# Idempotent. Invoked by scripts/04-apply-rebrand.sh with SRC as $1.
#
# Security: every bundled APK is signature-verified with apksigner (when the
# host tool is available) and, where a publisher signing cert is pinned below,
# the signer cert SHA-256 must match or the fetch fails closed. This prevents a
# compromised mirror from slipping a tampered APK into the image.
. "$(cd "$(dirname "$0")/../scripts" && pwd)/lib.sh"
load_config

SRC="${1:-$WL_SRC_DIR}"
[ -d "$SRC" ] || die "Source dir not found: $SRC"
require_cmd curl

PREBUILT="${SRC}/vendor/wraithlink/prebuilt-apps"
mkdir -p "$PREBUILT"
mk="${SRC}/vendor/wraithlink/wraithlink-apps.mk"
: > "$mk"
echo "# WraithLink bundled apps product fragment (generated)." >> "$mk"

# Locate apksigner (built as a host tool once the tree has been built once).
APKSIGNER=""
for c in "${SRC}/out/host/linux-x86/bin/apksigner" "$(command -v apksigner 2>/dev/null || true)"; do
  if [ -n "$c" ] && [ -x "$c" ]; then APKSIGNER="$c"; break; fi
done
[ -n "$APKSIGNER" ] || warn "apksigner not found (build the tree once); signature checks will be skipped."

fetch() { # name url dest
  if [ -f "$3" ]; then ok "cached: $1"; return 0; fi
  log "fetching $1"
  curl -fsSL --retry 3 --proto '=https' --tlsv1.2 "$2" -o "$3" \
    || { warn "failed to fetch $1 from $2 (place APK manually at $3)"; rm -f "$3"; return 1; }
}

verify_apk() { # file expected_cert_sha256(optional)
  local f="$1" want="$2" got out
  [ -f "$f" ] || { warn "missing $f"; return 1; }
  if [ -z "$APKSIGNER" ]; then
    warn "skipping signature check for $(basename "$f") (no apksigner)"; return 0
  fi
  # Host apksigner needs a JRE; build hosts often lack `java` on PATH.
  if ! command -v java >/dev/null 2>&1 && [ -z "${JAVA_HOME:-}" ]; then
    warn "skipping signature check for $(basename "$f") (no java for apksigner)"; return 0
  fi
  out="$("$APKSIGNER" verify "$f" 2>&1)" || {
    if echo "$out" | grep -qi 'java: not found\|Unable to locate.*java'; then
      warn "skipping signature check for $(basename "$f") (apksigner needs java)"; return 0
    fi
    warn "APK signature INVALID: $f"; return 1
  }
  if [ -n "$want" ]; then
    got="$("$APKSIGNER" verify --print-certs "$f" 2>/dev/null \
            | awk -F': ' '/certificate SHA-256 digest/{print $2; exit}' | tr 'A-F' 'a-f' | tr -d ' ')"
    if [ -n "$got" ] && [ "$got" != "$(echo "$want" | tr 'A-F' 'a-f')" ]; then
      warn "signer cert mismatch for $(basename "$f"): got $got want $want"; return 1
    fi
    ok "signer cert pinned-OK: $(basename "$f")"
  else
    ok "signature valid: $(basename "$f")"
  fi
  return 0
}

# Resolve the latest STABLE (non-alpha) Tor Browser aarch64 APK URL from the
# Tor Project distribution directory. Alpha dirs (e.g. 16.0a9) are excluded
# because they contain a letter and never match the digits-only version regex.
resolve_tor_stable_aarch64() {
  local base="https://dist.torproject.org/torbrowser/" ver
  ver="$(curl -fsSL "$base" \
          | grep -oE 'href="[0-9]+\.[0-9]+(\.[0-9]+)?/"' \
          | sed -E 's/href="([^"]+)\/"/\1/' | sort -V | tail -1)"
  [ -n "$ver" ] || return 1
  echo "${base}${ver}/tor-browser-android-aarch64-${ver}.apk"
}

# name | artifact | cert_sha256 (empty = signature-valid only) | url (empty = resolver)
FDROID_CERT="43238d512c1e5eb2d6569f4a3afbf5523418b82e0a3ed1552770abb9a9c9ccab"
ORBOT_CERT="6b79cb30d59278fd66b2740223e0592a1f8363274ac8498960491b0201b9b4f2"

# v1 lean ship: only F-Droid is fetched/preinstalled. Orbot / Tor Browser / Mullvad
# install from F-Droid. Remove stale prebuilts from earlier fat bundles.
rm -f "${PREBUILT}/Orbot.apk" "${PREBUILT}/TorBrowser.apk" "${PREBUILT}/Mullvad.apk"

fetch "F-Droid" "https://f-droid.org/F-Droid.apk" "${PREBUILT}/FDroid.apk" \
  && verify_apk "${PREBUILT}/FDroid.apk" "$FDROID_CERT" || rm -f "${PREBUILT}/FDroid.apk"

# APKs CANNOT be installed via PRODUCT_COPY_FILES (AOSP: "use BUILD_PREBUILT
# instead"). Register each present + verified APK as a presigned
# android_app_import module in Android.bp, then reference via PRODUCT_PACKAGES.
log "Registering verified APKs as android_app_import in ${PREBUILT}/Android.bp"
bp="${PREBUILT}/Android.bp"
echo "// Generated by WraithLink apply-bundled-apps.sh. Presigned, signature-verified prebuilt apps." > "$bp"
for apk in FDroid; do
  if [ -f "${PREBUILT}/${apk}.apk" ]; then
    cat >> "$bp" <<EOF

android_app_import {
    name: "WraithLink_${apk}",
    apk: "${apk}.apk",
    presigned: true,
    // Required for targetSdk >= 30: keep the v2+ signature intact.
    preprocessed: true,
    dex_preopt: {
      enabled: false,
    },
}
EOF
    echo "PRODUCT_PACKAGES += WraithLink_${apk}" >> "$mk"
    ok "  registered WraithLink_${apk}"
  else
    warn "  ${apk}.apk absent/failed verification - NOT bundled."
  fi
done

# WraithLink Messenger: Gradle-built, signed with dedicated app key, removable.
CHAT_STAGE="${WL_ROOT}/apps/chat/build-and-stage.sh"
if [ -x "$CHAT_STAGE" ]; then
  log "Building + staging WraithLink Messenger..."
  if "$CHAT_STAGE" "$SRC"; then
    ok "WraithLink Messenger staged."
  else
    warn "WraithLink Messenger build/stage failed — image will ship without it this pass."
  fi
else
  warn "apps/chat/build-and-stage.sh missing/not executable; messenger not bundled."
fi

# Apps repo: only rewrite when WL_APPS_REPO_HOST is set (must be a live mirror).
STORE_SRC="${SRC}/packages/apps/Apps"
if [ -n "${WL_APPS_REPO_HOST:-}" ] && [ -d "$STORE_SRC" ]; then
  log "Configuring Apps repo host -> ${WL_APPS_REPO_HOST}"
  grep -rl "apps.grapheneos.org" "$STORE_SRC" 2>/dev/null | while read -r f; do
    sed -i "s#apps.grapheneos.org#${WL_APPS_REPO_HOST}#g" "$f"
  done
  ok "Repointed Apps repo URLs to ${WL_APPS_REPO_HOST}"
elif [ -d "$STORE_SRC" ]; then
  ok "Leaving Apps repo at apps.grapheneos.org (set WL_APPS_REPO_HOST to override)."
else
  warn "packages/apps/Apps not found; store step skipped."
fi

ok "Bundled apps wired (v1: F-Droid + optional Chat). Sandboxed Play remains first-run only."
