#!/usr/bin/env bash
# Build WraithLink-Messenger (separate repo) and stage into the product image.
# Clone: https://github.com/sk1tzwzd/WraithLink-Messenger
# Override path: export WL_CHAT_SRC=/path/to/WraithLink-Messenger
set -euo pipefail
. "$(cd "$(dirname "$0")/../../scripts" && pwd)/lib.sh"
load_config

SRC="${1:-$WL_SRC_DIR}"
CHAT_ROOT="$(resolve_chat_src)"
PREBUILT="${SRC}/vendor/wraithlink/prebuilt-apps"
mkdir -p "$PREBUILT"

ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-${HOME}/android-sdk}"
export ANDROID_SDK_ROOT ANDROID_HOME="$ANDROID_SDK_ROOT"

cat > "${CHAT_ROOT}/local.properties" <<EOF
sdk.dir=${ANDROID_SDK_ROOT}
EOF

KEYSTORE="${WL_KEYS_DIR}/wraithlink-chat.jks"
KEY_ALIAS="wraithlink-chat"
if [ ! -f "$KEYSTORE" ]; then
  warn "Chat signing key missing at ${KEYSTORE}."
  warn "Run scripts/03-gen-keys.sh (or create the keystore) before staging a release APK."
  SKIP_SIGN=1
else
  SKIP_SIGN=0
fi

log "Building WraithLink messenger from ${CHAT_ROOT}"
cd "$CHAT_ROOT"
[ -x ./gradlew ] || die "gradlew missing in ${CHAT_ROOT}"
./gradlew :app:assembleRelease --no-daemon

CANDIDATE="$(ls -1 "${CHAT_ROOT}/app/build/outputs/apk/release/"*.apk 2>/dev/null | head -1 || true)"
[ -n "$CANDIDATE" ] || die "No release APK produced under app/build/outputs/apk/release/"

OUT_APK="${PREBUILT}/WraithLinkChat.apk"
if [ "$SKIP_SIGN" = "1" ]; then
  cp -f "$CANDIDATE" "$OUT_APK"
  warn "Staged UNSIGNED chat APK at ${OUT_APK} (debug only)."
else
  PASS="${WL_CHAT_KEY_PASSPHRASE:-${WL_KEY_PASSPHRASE:-}}"
  [ -n "$PASS" ] || die "Set WL_CHAT_KEY_PASSPHRASE (or WL_KEY_PASSPHRASE) to unlock ${KEYSTORE}"
  APKSIGNER=""
  for c in "${SRC}/out/host/linux-x86/bin/apksigner" \
           "${ANDROID_SDK_ROOT}/build-tools/35.0.0/apksigner" \
           "$(command -v apksigner 2>/dev/null || true)"; do
    if [ -n "$c" ] && [ -x "$c" ]; then APKSIGNER="$c"; break; fi
  done
  [ -n "$APKSIGNER" ] || die "apksigner not found"
  rm -f "$OUT_APK"
  "$APKSIGNER" sign --ks "$KEYSTORE" --ks-key-alias "$KEY_ALIAS" \
    --ks-pass "pass:${PASS}" --key-pass "pass:${PASS}" \
    --out "$OUT_APK" "$CANDIDATE"
  "$APKSIGNER" verify "$OUT_APK"
  ok "Signed WraithLinkChat.apk -> ${OUT_APK}"
fi

bp="${PREBUILT}/Android.bp"
if [ ! -f "$bp" ]; then
  echo "// Generated by WraithLink apply-bundled-apps / build-and-stage." > "$bp"
fi
if ! grep -q 'name: "WraithLink_Chat"' "$bp" 2>/dev/null; then
  cat >> "$bp" <<'EOF'

android_app_import {
    name: "WraithLink_Chat",
    apk: "WraithLinkChat.apk",
    presigned: true,
    preprocessed: true,
    dex_preopt: {
        enabled: false,
    },
}
EOF
fi

mk="${SRC}/vendor/wraithlink/wraithlink-apps.mk"
mkdir -p "$(dirname "$mk")"
touch "$mk"
if ! grep -q 'PRODUCT_PACKAGES += WraithLink_Chat' "$mk" 2>/dev/null; then
  echo "PRODUCT_PACKAGES += WraithLink_Chat" >> "$mk"
fi
ok "WraithLink_Chat registered in PRODUCT_PACKAGES (preinstalled, removable)."
